# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 853d7b68a5e0573fb37ed40ce455ab52e546ff8de7b0fda53f0898459e97f3f10b690824f4cd6605254c3ac078780ca7d3ad650ba84ce7c807428cc3f7e56081

test:
  secret_key_base: f07897b6f4af539db848bc69f49b6b5d7eef4f4320a5177a8bd3afd710e1e11b203d526f195ecd7660db5215d6a9c3c9148889a5113983d40b0d540ed9ea11b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
